### ISSUE TITLE
needs minor fixups for compatibility with sklearn >= 0.17

### ISSUE THREAD

**Issue by yarikoptic** [pyhrf/pyhrf#142]
Ward* constructs were deprecated in favor of AgglomerativeClustering.
```
..........................................
======================================================================
ERROR: test_ward_spatial_cmd (pyhrf.test.test_parcellation.CmdParcellationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/deb/perspect/pyhrf/venv-trusty/local/lib/python2.7/site-packages/pyhrf-0.4.1.post1-py2.7-linux-x86_64.egg/pyhrf/test/test_parcellation.py", line 236, in test_ward_spatial_cmd
    raise Exception('"' + cmd + '" did not execute correctly')
Exception: "pyhrf_parcellate_glm -m /tmp/pyhrf_NSxGr6/mask.nii /tmp/pyhrf_NSxGr6/p1.nii /tmp/pyhrf_NSxGr6/p2.nii -o /tmp/pyhrf_NSxGr6/parcellation_output_test.nii -v 30 -n 4 -t ward_spatial " did not execute correctly

======================================================================
ERROR: test_ward_spatial_real_data (pyhrf.test.test_parcellation.CmdParcellationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/deb/perspect/pyhrf/venv-trusty/local/lib/python2.7/site-packages/pyhrf-0.4.1.post1-py2.7-linux-x86_64.egg/pyhrf/test/test_parcellation.py", line 280, in test_ward_spatial_real_data
    raise Exception('"' + cmd + '" did not execute correctly')
Exception: "pyhrf_parcellate_glm -m /home/yoh/deb/perspect/pyhrf/venv-trusty/lib/python2.7/site-packages/pyhrf-0.4.1.post1-py2.7-linux-x86_64.egg/pyhrf/datafiles/subj0_parcellation.nii.gz /tmp/pyhrf_fjTCWS/beta_audio.nii /tmp/pyhrf_fjTCWS/beta_video.nii /tmp/pyhrf_fjTCWS/beta_drift_1.nii /tmp/pyhrf_fjTCWS/beta_drift_2.nii /tmp/pyhrf_fjTCWS/beta_drift_3.nii /tmp/pyhrf_fjTCWS/beta_drift_4.nii /tmp/pyhrf_fjTCWS/beta_constant.nii -o /tmp/pyhrf_fjTCWS/parcellation_output_test_real_data.nii -v 30 -n 10 -t ward_spatial " did not execute correctly

======================================================================
ERROR: test_ward_spatial_scikit (pyhrf.test.test_parcellation.ParcellationMethodTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/deb/perspect/pyhrf/venv-trusty/local/lib/python2.7/site-packages/pyhrf-0.4.1.post1-py2.7-linux-x86_64.egg/pyhrf/test/test_parcellation.py", line 153, in test_ward_spatial_scikit
    labels = parcellation_ward_spatial(X, n_clusters=5, graph=graph)
  File "/home/yoh/deb/perspect/pyhrf/venv-trusty/local/lib/python2.7/site-packages/pyhrf-0.4.1.post1-py2.7-linux-x86_64.egg/pyhrf/parcellation.py", line 95, in parcellation_ward_spatial
    from sklearn.cluster import Ward
ImportError: cannot import name Ward

======================================================================
ERROR: test_ward_spatial_scikit_with_mask (pyhrf.test.test_parcellation.ParcellationMethodTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/deb/perspect/pyhrf/venv-trusty/local/lib/python2.7/site-packages/pyhrf-0.4.1.post1-py2.7-linux-x86_64.egg/pyhrf/test/test_parcellation.py", line 184, in test_ward_spatial_scikit_with_mask
    labels = parcellation_ward_spatial(X, n_clusters=4, graph=graph)
  File "/home/yoh/deb/perspect/pyhrf/venv-trusty/local/lib/python2.7/site-packages/pyhrf-0.4.1.post1-py2.7-linux-x86_64.egg/pyhrf/parcellation.py", line 95, in parcellation_ward_spatial
    from sklearn.cluster import Ward
ImportError: cannot import name Ward

----------------------------------------------------------------------
Ran 240 tests in 149.846s

FAILED (errors=4, skipped=2)
(venv-trusty)(git)/home/yoh/deb/perspect/pyhrf:[master]
#31 !1119 [0].....................................:Mon Jan 25 15:09:55:.
hopa(trusty):~/deb/perspect/pyhrf
$> apt-cache policy python-sklearn
python-sklearn:
  Installed: 0.17.0-3~nd14.04+1
  Candidate: 0.17.0-3~nd14.04+1
  Version table:
 *** 0.17.0-3~nd14.04+1 0
        500 http://neuro.debian.net/debian/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     0.14.1-2 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
```

**Comment by thperret** [comment]
I just opened the same issue ;-)
Thanks
