### ISSUE TITLE
[deps] unittests errors with PIL (Pillow)

### ISSUE THREAD

**Issue by thperret** [pyhrf/pyhrf#146]
At first look, it's seems to comes from Pillow dependency but there's investigations to do.

```
======================================================================

ERROR: test_simulate_asl_full_physio_outputs (pyhrf.test.test_sandbox_physio.SimulationTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/thperret/pyhrf/python/pyhrf/test/test_sandbox_physio.py", line 54, in test_simulate_asl_full_physio_outputs

    phy.simulate_asl_full_physio(self.tmp_path)

  File "/home/travis/build/thperret/pyhrf/python/pyhrf/sandbox/physio.py", line 415, in simulate_asl_full_physio

    simbase.simulation_save_vol_outputs(simulation, output_dir)

  File "/home/travis/build/thperret/pyhrf/python/pyhrf/boldsynth/scenarios.py", line 857, in simulation_save_vol_outputs

    axes_domains={'time': np.arange(brfs_vol.shape[0]) * dt})

  File "/home/travis/build/thperret/pyhrf/python/pyhrf/ndarray.py", line 90, in __init__

    % (len(axes_names), nbDims, str(axes_names)))

Exception: length of axes_names (4) is different from nb of dimensions (5).

Got axes names: ['time', 'sagittal', 'coronal', 'axial']

-------------------- >> begin captured logging << --------------------

PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13

PIL.PngImagePlugin: DEBUG: STREAM sRGB 41 1

PIL.PngImagePlugin: DEBUG: sRGB 41 1 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM PLTE 54 96

PIL.PngImagePlugin: DEBUG: STREAM pHYs 162 9

PIL.PngImagePlugin: DEBUG: STREAM tIME 183 7

PIL.PngImagePlugin: DEBUG: tIME 183 7 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM tEXt 202 25

PIL.PngImagePlugin: DEBUG: STREAM IDAT 239 17

PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13

PIL.PngImagePlugin: DEBUG: STREAM sRGB 41 1

PIL.PngImagePlugin: DEBUG: sRGB 41 1 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM PLTE 54 96

PIL.PngImagePlugin: DEBUG: STREAM pHYs 162 9

PIL.PngImagePlugin: DEBUG: STREAM tIME 183 7

PIL.PngImagePlugin: DEBUG: tIME 183 7 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM tEXt 202 25

PIL.PngImagePlugin: DEBUG: STREAM IDAT 239 17

PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13

PIL.PngImagePlugin: DEBUG: STREAM sRGB 41 1

PIL.PngImagePlugin: DEBUG: sRGB 41 1 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM PLTE 54 96

PIL.PngImagePlugin: DEBUG: STREAM pHYs 162 9

PIL.PngImagePlugin: DEBUG: STREAM tIME 183 7

PIL.PngImagePlugin: DEBUG: tIME 183 7 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM tEXt 202 25

PIL.PngImagePlugin: DEBUG: STREAM IDAT 239 17

--------------------- >> end captured logging << ---------------------

======================================================================

FAIL: test_simulate_asl_full_physio (pyhrf.test.test_sandbox_physio.SimulationTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/thperret/pyhrf/python/pyhrf/test/test_sandbox_physio.py", line 47, in test_simulate_asl_full_physio

    self.assertEqual(r['labels_vol'].shape, (3, 1, 2, 2))

AssertionError: Tuples differ: (3, 1, 2, 2, 3) != (3, 1, 2, 2)

First tuple contains 1 additional elements.

First extra element 4:

3

- (3, 1, 2, 2, 3)

?            ---

+ (3, 1, 2, 2)

-------------------- >> begin captured logging << --------------------

PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13

PIL.PngImagePlugin: DEBUG: STREAM sRGB 41 1

PIL.PngImagePlugin: DEBUG: sRGB 41 1 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM PLTE 54 96

PIL.PngImagePlugin: DEBUG: STREAM pHYs 162 9

PIL.PngImagePlugin: DEBUG: STREAM tIME 183 7

PIL.PngImagePlugin: DEBUG: tIME 183 7 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM tEXt 202 25

PIL.PngImagePlugin: DEBUG: STREAM IDAT 239 17

PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13

PIL.PngImagePlugin: DEBUG: STREAM sRGB 41 1

PIL.PngImagePlugin: DEBUG: sRGB 41 1 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM PLTE 54 96

PIL.PngImagePlugin: DEBUG: STREAM pHYs 162 9

PIL.PngImagePlugin: DEBUG: STREAM tIME 183 7

PIL.PngImagePlugin: DEBUG: tIME 183 7 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM tEXt 202 25

PIL.PngImagePlugin: DEBUG: STREAM IDAT 239 17

PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13

PIL.PngImagePlugin: DEBUG: STREAM sRGB 41 1

PIL.PngImagePlugin: DEBUG: sRGB 41 1 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM PLTE 54 96

PIL.PngImagePlugin: DEBUG: STREAM pHYs 162 9

PIL.PngImagePlugin: DEBUG: STREAM tIME 183 7

PIL.PngImagePlugin: DEBUG: tIME 183 7 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM tEXt 202 25

PIL.PngImagePlugin: DEBUG: STREAM IDAT 239 17

--------------------- >> end captured logging << ---------------------

======================================================================

FAIL: test_simulate_asl_physio_rfs (pyhrf.test.test_sandbox_physio.SimulationTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/thperret/pyhrf/python/pyhrf/test/test_sandbox_physio.py", line 73, in test_simulate_asl_physio_rfs

    self.assertEqual(r['labels_vol'].shape, (3, 1, 2, 2))

AssertionError: Tuples differ: (3, 1, 2, 2, 3) != (3, 1, 2, 2)

First tuple contains 1 additional elements.

First extra element 4:

3

- (3, 1, 2, 2, 3)

?            ---

+ (3, 1, 2, 2)

-------------------- >> begin captured logging << --------------------

PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13

PIL.PngImagePlugin: DEBUG: STREAM sRGB 41 1

PIL.PngImagePlugin: DEBUG: sRGB 41 1 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM PLTE 54 96

PIL.PngImagePlugin: DEBUG: STREAM pHYs 162 9

PIL.PngImagePlugin: DEBUG: STREAM tIME 183 7

PIL.PngImagePlugin: DEBUG: tIME 183 7 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM tEXt 202 25

PIL.PngImagePlugin: DEBUG: STREAM IDAT 239 17

PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13

PIL.PngImagePlugin: DEBUG: STREAM sRGB 41 1

PIL.PngImagePlugin: DEBUG: sRGB 41 1 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM PLTE 54 96

PIL.PngImagePlugin: DEBUG: STREAM pHYs 162 9

PIL.PngImagePlugin: DEBUG: STREAM tIME 183 7

PIL.PngImagePlugin: DEBUG: tIME 183 7 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM tEXt 202 25

PIL.PngImagePlugin: DEBUG: STREAM IDAT 239 17

PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13

PIL.PngImagePlugin: DEBUG: STREAM sRGB 41 1

PIL.PngImagePlugin: DEBUG: sRGB 41 1 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM PLTE 54 96

PIL.PngImagePlugin: DEBUG: STREAM pHYs 162 9

PIL.PngImagePlugin: DEBUG: STREAM tIME 183 7

PIL.PngImagePlugin: DEBUG: tIME 183 7 (unknown)

PIL.PngImagePlugin: DEBUG: STREAM tEXt 202 25

PIL.PngImagePlugin: DEBUG: STREAM IDAT 239 17

--------------------- >> end captured logging << ---------------------
```

**Comment by thperret** [comment]
After some investigation, it seems to come from `scipy.misc.fromimage` and a bug in PIL, see https://github.com/python-pillow/Pillow/issues/350 and https://github.com/scipy/scipy/issues/2138

I'm working on a workaround
